let cars = [
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
    {image:'https://apollo-singapore.akamaized.net/v1/files/poyvj8lhhu6l-IN/image;s=300x600;q=60',
    price:"₹ 4,35,000",
    post_year:"2014",
    post_date:'Aug02',
    brand:'Maruti',
    model:'Maruti Suzuki Swift Dzire',
    state:"Odisha",
    place:"Bhubaneswar",
    address:"Satya Vihar",
    fuel:"Petrol",
    transmission:"Manual",
    km_driven:"70,000 km",
    id:'1',
},
  
 
]
let container = document.getElementById('container');
function appendData(cars){
    cars.forEach((el)=>{
        //Create div to append entire details of a product

        let div = document.createElement('div');
        //Create img_div to append the image

        let img_div = document.createElement('div');
        img_div.setAttribute("class","img_div")
        let image = document.createElement('img');
        image.src = el.image;
        img_div.append(image)
        //Create details_div to append all the details of the product like price,Postdate,etc.

        let details_div = document.createElement('div');
        details_div.setAttribute('class','details_div')
        let price = document.createElement('h3');
        price.innerText = el.price
        let year_km = document.createElement('p');
        year_km.innerText =`${el.post_year}-${el.km_driven}`;
        let model = document.createElement('h4');
        model.innerText = el.model
        //Create another address_date_div and append it to details div
        let address_date_div = document.createElement('div');
        address_date_div.setAttribute('class','address_date_div')
        let address = document.createElement('p');
        address.innerText = el.address;
        let date = document.createElement('p');
        date.innerText = el.post_date;
        address_date_div.append(address,date)
        details_div.append(price,year_km,model,address_date_div);
        div.append(img_div,details_div);
        container.append(div)
        
    })
}
appendData(cars)

let moving1 = document.getElementById('moving1');
let category = document.querySelector('.category');
let pehla = document.querySelector('.pehla');
let dusra = document.querySelector('.dusra');
let category_bottom = document.querySelector('.category_bottom');

category.addEventListener('click',()=>{
    pehla.classList.toggle('hidden')
    dusra.classList.toggle('hidden')
    moving1.classList.toggle('rotate')
    category_bottom.classList.toggle('category_bottom_hidden')
})
let moving2 = document.getElementById('moving2');
let locate = document.querySelector('.location');
let india = document.querySelector('.india');
let addstate = document.querySelector('.addstate');
let state = document.getElementById('state')
let chotaindia = document.querySelector('.chotaindia');
locate.addEventListener('click',()=>{
    moving2.classList.toggle('rotate');
    state.classList.toggle('hidden')
    chotaindia.classList.toggle('chotaindia_hidden')
})

let moving3 = document.getElementById('moving3');
let brand_model = document.querySelector('.brand_model');
let search_brand_model = document.querySelector('.search_brand_model')
let allbrands = document.getElementById('allbrands');
let brands = document.querySelector('.brands')
let allmodels = document.getElementById('allmodels');
let models = document.querySelector('.models');
brand_model.addEventListener('click',()=>{
    moving3.classList.toggle('rotate');
    search_brand_model.classList.toggle('hide');
    allmodels.classList.toggle('hidden')
    models.classList.toggle('hidden')
    allbrands.classList.toggle('hidden')
    brands.classList.toggle('hidden')
})